### PR TITLE
Add me to the player list

### PR DESCRIPTION
**Pull request by TheJhyde**
I wish to be added to the player list. Just added a single line to players.txt

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Can you put your GitHub username in players.txt instead of your first name? That's how the system knows who's playing.

**Comment by jeffkaufman** [comment]
Once @dchudz approves we can rerun the build and then you should be able to merge

**Comment by jeffkaufman** [comment]
I'm ok with this going in, as long as you promise to submit a PR to remove yourself from players.txt if you get bored and want to stop playing.

(This is only needed until we have a fix for https://github.com/jeffkaufman/nomic/issues/19)

**Comment by jeffkaufman** [comment]
This is green, so you should be able to click "merge pull request" and merge this to join.  I could do it, but I want to make sure it works for you.

**Comment by TheJhyde** [comment]
Yes, it does!

**Pull request merged**
