### PR TITLE
Removing myself from the game

### PR DESCRIPTION
**Pull request by pavellishin**
I'm realizing that I'm not contributing enough with pull request reviews, and slowing the game down. Until I can dedicate more time to this, I'm going to step out :/

### CODE REVIEW

**Comment by jeffkaufman** [comment]
I think maybe we should put the game on hold then?  With @pavellishin out, @jburger424 not participating very actively, and me feeling a bit played out this might be a good time to stop?

**Comment by jeffkaufman** [comment]
@tnelling what do you think?

**Comment by tnelling** [comment]
When you say "played out", are you saying you think the idea has run its course permanently, or just that you want to take a break?

I'm still interested in trying to build out the framework (I was always more interested in that than actually winning). But there's no sense in doing that if no one is going to use it.

**Comment by jeffkaufman** [comment]
I think there's still fun to be had with the idea, but I'm less interested than I was.

If there was a group of say four people excited to play again in a few months I'd be up for that.

**Comment by tnelling** [comment]
Seems reasonable. I'd like to finish up the work I have going on right now. And I'd like to look into adding more tests to the test suite. But I don't think anyone should feel obligated to unblock me.

**Pull request merged**
