### PR TITLE
this PR will erroneously fail checks

### PR DESCRIPTION
**Pull request by jeffkaufman**

### CODE REVIEW

**Comment by tnelling** [comment]
Is this because the user is returned from util.users because you're creating it? I hadn't considered that...

**Comment by jeffkaufman** [comment]
> Is this because the user is returned from util.users because you're creating it? I hadn't considered that...

Yes.  The PR runs first on master and passes, and then on the branch and fails.  On the branch this user looks like an existing user.

But the "is this creating an existing user" check isn't needed, because "this PR adds players/foo/bonuses/initial" tells you that it's adding a user.

**Comment by tnelling** [comment]
That's only true if we never allow anyone into the game without an initial bonus file.

**Comment by tnelling** [comment]
I think a better check would be that there is no other file under `players/<username>`

**Comment by tnelling** [comment]
I'm going to put a fix into #242 because I think we shouldn't have this allowing dummy users through anyway.

**Comment by jeffkaufman** [comment]
You could have the PR assert that one of the two is true:

1. `players/username` does not exist
2. `players/username` contains only a single directory, `bonus`, which contains a single file, `initial`

The first will be true on master, the second on the PR branch.

**Comment by tnelling** [comment]
Yeah, I should have been clearer - we check that there are no files other than initial, and also that initial is being added as part of the PR. The second part is already in the rule, so we just need to add the first.

**Pull request closed without merging**
