### PR TITLE
named-bonuses: alternative implementation

### PR DESCRIPTION
**Pull request by jeffkaufman**
This is an alternative to #47, where the point value is in the filename instead of the file body.  Suggested in the comments on #50, the idea is this makes it easier to parse diffs that work with points.

I also added two example files to my directory, one showing point gain and one showing point loss, so you can see what negative numbers look like.

I don't have strong feelings between this and #47, and would be happy with either.

### CODE REVIEW

**Comment by sligocki** [comment]
I still prefer #47, so I will not approve this one (and encourage you all to approve #47 :) ). But I will not veto either.

**Comment by pavellishin** [comment]
> the point value is in the filename instead of the file body

I hate it. It seems weird and unclean to store points in the filename. But I haven't looked at the code to see how much easier this makes validating point values in diffs, and won't have time today - so to make up for my absence the last few days I'll just approve both :)

**Comment by jeffkaufman** [comment]
This now has merge conflicts.  I'll fix this if someone asks me to, but I think #47 is better

**Comment by tnelling** [comment]
Closing because everyone seems to prefer #47

**Pull request closed without merging**
