### PR TITLE
join game

### PR DESCRIPTION
**Pull request by dnathe4th**

### CODE REVIEW

**Comment by dnathe4th** [comment]
Blocked by #256

**Comment by tnelling** [comment]
Can you submit another PR where you start with -1 points? This is for the purpose of the tests I'm trying to add in #242. You can immediately close it afterward, it only needs to exist for the test's benefit.

**Comment by tnelling** [comment]
Well that works, if you want to close this one and open another join PR.

**Comment by dnathe4th** [comment]
Just for my clarity, open another with -1 as the initial points same as this? Why doesn't this PR work?

**Comment by tnelling** [comment]
For the purposes of the tests I'm trying to add, I have two different test cases. One has a new user joining with -1 points (which should be rejected b/c points shouldn't be negative), and one with 0 points (which should be accepted). But you can't do both in the same PR.

**Comment by dnathe4th** [comment]
Cool I added #258 to be the zero point initial test case, and this one to be -1.

**Comment by tnelling** [comment]
Thanks!

**Comment by dnathe4th** [comment]
What's the path forward here? Wait on #242 to land?

**Comment by tnelling** [comment]
To be clear, I closed this because it's the negative point version. #258 should be fine. And we can merge you in without #242.

That said, there's a couple of paths forward:
1. Merge you in directly without using the new-users rule shortcut.
2. Merge @jeffkaufman's departure first, then merge #242, which is blocked by his (stale) rejection, then use the new-users rule.
3. Create a new PR with the same changes as #242, merge it, then use the new-users rule.
Optional: consider also creating & merging a PR to remove @jburger424 to speed things up, not just now, but in the future.

**Comment by dnathe4th** [comment]
I vote for the second option because it seems like the most "correct" based on the current rules of the game.

**Pull request closed without merging**
