### PR TITLE
Adding .gitignore file

### PR DESCRIPTION
**Pull request by pavellishin**
Tired of seeing this in this project. I already have `venv` in my `~/.gitignore`, but I don't want to add `.vscode` to that.

### CODE REVIEW

**Comment by pavellishin** [comment]
> What files you want to ignore will depend on your dev environment. Why not just put `.gitignore` in your `.gitignore`?

I didn't know that was an option!

**Comment by pavellishin** [comment]
Wait, it doesn't appear to work; it doesn't ignore itself.

**Comment by jeffkaufman** [comment]
```
$ touch foo
$ git status
Untracked files:
	foo
$ echo foo > .gitignore
$ git status
Untracked files:
	.gitignore
$ echo .gitignore >> .gitignore
$ git status 
nothing to commit, working tree clean
```

**Comment by pavellishin** [comment]
Whoops, it works - I did:

`git checkout master`
`git checkout <this-branch> .gitignore`

which added it to the index. Running `git reset .gitignore` has solved my woes! Thank you!

**Pull request closed without merging**
