### PR TITLE
Show us the stragglers who didn't approve a PR.

### PR DESCRIPTION
**Pull request by pavellishin**
Shows us the players who *didn't* approve a PR, for more convenient pings.

### CODE REVIEW

**Comment by jmitchell** [comment]
Might as well make the distinction between non-participation and rejection explicit. I could be persuaded otherwise if there's a good reason we shouldn't.

**Comment by tnelling** [comment]
I disagree. I have no guarantee that said PR will ever go through (in the general case - in this instance I imagine it would). And making it better is what requesting changes is for. I do understand the notion of keeping things scoped, but I don't think this is out of scope.

**Comment by pavellishin** [comment]
I AGREE WITH THE GUY WHO SAYS MY CODE IS 👍 

(but ok, i'll make the change tonight or tomorrow)

**Comment by jeffkaufman** [comment]
@tnelling 

> I disagree. I have no guarantee that said PR will ever go through (in the general case - in this instance I imagine it would).

My view is, if a PR makes things better from where they are now, we should merge it.  If you have a way to make a PR better from there you can either ask for it or do it yourself.  Using a good PR as leverage to get someone to make an even better PR is annoying.

(If a PR is bad-as-is though, of course it's fine to reject)

What do others think?

**Comment by jmitchell** [comment]
Thanks for making the suggested improvement, @pavellishin.

Regarding discussions here about procedural best practices, please see #52.

**Comment by jeffkaufman** [comment]
I don't think we need this now that we have the [dashboard](https://www.jefftk.com/nomic) though I won't retract my review

**Comment by pavellishin** [comment]
True, though I think it's still convenient. I'd still like to merge this in.

**Comment by tnelling** [comment]
I don't see any reason this can't be reviewed. If we don't want it any more because of the dashboard, we can reject or close it, though I tend to agree with @pavellishin that it's nice to able to see the output in the build itself (not least because the dashboard might disagree, see #67

**Comment by pavellishin** [comment]
Whoops; I forgot to add the label, thank you!

**Pull request merged**
