### PR TITLE
remove dchudz as a player

### PR DESCRIPTION
**Pull request by dchudz**
I don't think I'm really going to play. Thanks everyone.

### CODE REVIEW

**Comment by dchudz** [comment]
I can't leave without 1 more person's OK

**Comment by jeffkaufman** [comment]
Funny: we have 6 of 9 approvals so this should be able to go in, except once we lose David we have 5 of 8 approvals.  Which means while this PR validates on master it doesn't validate on the branch.

**Comment by jeffkaufman** [comment]
@dchudz would you mind approving #68 and #69 (removing other inactive players) before you go?

**Comment by dchudz** [comment]
merged #68 and #69, and merged master into this PR, so now it should pass after people approve again

**Pull request merged**
