### PR TITLE
Join with 0 points initial bonus

### PR DESCRIPTION
**Pull request by dnathe4th**

### CODE REVIEW

**Comment by dnathe4th** [comment]
Thanks! can you add me as a repo contributor too?

**Comment by tnelling** [comment]
I can't, but @jeffkaufman can. In theory, we could use #92 to address this limitation, but I never thought up a way to work around the issues discussed there.

**Comment by dnathe4th** [comment]
If Jeff's out should we just move over to a fork and get out of his hair?

**Comment by tnelling** [comment]
We could, but he's doing several things to support the game right now, including hosting the GitHub proxy and the dashboard. Obviously a fork could function without the dashboard (it's a nice to have), but the proxy is pretty critical. Given that we only have two players right now, it seems like more trouble than it's worth to find alternatives for those.

I also don't know if he's permanently out or not (earlier he indicated he might not be).

**Comment by dnathe4th** [comment]
Fair enough maybe I misunderstood his position. Happy to stay here until we hear otherwise.

**Comment by jeffkaufman** [comment]
sent collaborator invite to @dnathe4th 

I don't mind continuing to host, though I'm not up for playing myself right now.  I hope you do interesting things with the game!

**Pull request merged**
