### PR TITLE
add tests

### PR DESCRIPTION
**Pull request by jeffkaufman**
Make it possible to write tests for rules.

A test is in the form "expect that running rule X on PR #Y has result Z".

This is enough for testing points transfer.  In order to test things like "block recent" we'll need to add something with (partly?) synthesized PRs so we can mock the timing.  But that should come later.

### CODE REVIEW

**Comment by tnelling** [comment]
To clarify, the intent here is to verify that subsequent PRs do not modify the intended behavior of existing rules?

**Comment by jeffkaufman** [comment]
@tnelling yes.  Just like normal tests for software.

I found that to make sure my PRs were working I had a series of `./run.sh NN` calls I would run.  Remembering what PR number I expected to have what output was getting annoying, so I wanted to automate it.

**Comment by tnelling** [comment]
I guess what confuses me is that the test itself is also a rule.

**Comment by jeffkaufman** [comment]
@tnelling Yup!  Just like how our type checking is a rule.  Everything should be a rule!

(It's nice to have a framework!)

**Comment by jeffkaufman** [comment]
@pavellishin @jburger424 needs review

**Pull request merged**
