### PR TITLE
players: switch to a directory

### PR DESCRIPTION
**Pull request by jeffkaufman**
Currently, when new players are added that makes merge conflicts, and requires
a lot of re-approvals.  An easy way to avoid this is to use a directory instead
of a file.

Also add everyone who has asked to be added:
 * Closes #11
 * Closes #12
 * Closes #15
 * Closes #20
 * Closes #22

We should probably merge #23 first, so we don't get stuck if we lose someone
(#19).

### CODE REVIEW

**Comment by tnelling** [comment]
I would approve this change if I could.

**Comment by pavellishin** [comment]
Oh, neat, I didn't know you could open PRs that close other PRs. How does that work?

**Comment by pavellishin** [comment]
@guoruibiao plz

**Comment by pavellishin** [comment]
Also, it's funny that a person who isn't *yet* technically a player is blocking this. I guess in the future this won't be an issue - given that people will be adding themselves, and thus will implicitly approve their PRs.

**Comment by guoruibiao** [comment]
approval 👍

**Pull request merged**
