### PR TITLE
Update validate.py with four space tabs, some PEP8, minor fixes

### PR DESCRIPTION
**Pull request by vesche**
This is a democracy right? Two spaces tabs look awful.

### CODE REVIEW

**Comment by pavellishin** [comment]
You know, I was about to call you a monster, but that does look nicer. At least on my big work monitor :P

**Comment by pavellishin** [comment]
I'm going to have to review this later, there's a lot of diff here, and I'm afraid you're sneaking something clever in there :P

**Comment by jeffkaufman** [comment]
Want to add pep8 validation with `flake8` or something as a merge requirement?  Otherwise this isn't going to keep nice!

**Comment by vesche** [comment]
@pavellishin 

A maliciously great idea in retrospect!

However, [this](https://github.com/jeffkaufman/nomic/blob/959157699afc286471454b824ba04fd3f64be669/validate.py#L110) is the only code that I actually changed:

```
reviews.pop(user, None)
```

Which previously was:

```
try:
    del reviews[user]
except KeyError:
    pass # No past rejections for this user.
```

@jeffkaufman 
I agree, looks like it would take some updates to the `.travis.yml`.

**Comment by jeffkaufman** [comment]
@vesche changes to Travis would be the standard way to do it, but you could just put a subprocesses call in validate.py

**Comment by jeffkaufman** [comment]
also, this isn't surprising since I wrote the initial stuff, but I much prefer two space tabs

**Comment by vesche** [comment]
Well if #76 goes through this PR is going to be moot. I'll close this.

I seriously have a hard time looking at the code with 2 space tabs. I think enough members of this democracy and I can make it happen. Almost everyone uses 4 space tabs @jeffkaufman ...

**Comment by pavellishin** [comment]
@vesche is it possible to adjust your editor to silently display leading spaces as twice-as-wide?

**Pull request closed without merging**
