### PR TITLE
Block on adherence to pep8

### PR DESCRIPTION
**Pull request by tnelling**
Adding a rule to block if the code does not adhere to pep8, and refactoring the existing code to adhere to it. Max line length is configurable, but tab size is not, so a lot of this is changing from 2 to 4 spaces. I set max line length to 120 to match the default in pycharm, since we were already overflowing the pep default of 79 as a result of the tab sizes.

If you turn off whitespace changes, the diff is a lot easier to read.

### CODE REVIEW

**Comment by tnelling** [comment]
I can't find an option to configure indent size in pep8 to 2 spaces, and those errors are a solid majority of what pep8 finds in this repo, which means either:

1. I abandon this and we don't use pep8
2. We turn off the indent rule (which seems like a big loss in python)
3. This is a super gross PR that changes the indents to 4
4. ... I'm wrong, and it is configurable, and someone knows how? Max line length is configurable, not sure why indent size wouldn't be.

What are people's thoughts? I'm not going to pursue this if no one wants it anyway. I do tend to agree with the comments from awhile ago that it would be nice for the automatic pep8 checking in PyCharm to work with this repo, so I'm okay with doing 3 at an opportune time.

@jeffkaufman @jburger424 @pavellishin

**Comment by pavellishin** [comment]
I'm ok with a gross PR; I rejected the last one because it _also_ did a little bit of refactoring, and I didn't trust the possible shenanigans.

**Comment by tnelling** [comment]
The PR actually isn't bad at all if you turn off whitespace changes. I had to make very few other changes.

**Comment by tnelling** [comment]
> I haven't reviewed closely with whitespace diffs enabled, so if you managed to sneak something by us by changing an indentation level somewhere that's very impressive.

That is definitely beyond my capabilities.

**Comment by jeffkaufman** [comment]
> That is definitely beyond my capabilities.

I don't know. Unindenting the end of a `for` so the second half only runs once? I did check for that but might have missed one.

**Comment by tnelling** [comment]
Well sure, but there would have to be a relevant loop already set up.

**Pull request merged**
