### PR TITLE
time: refactor, add notion of days a PR has been sitting

### PR DESCRIPTION
**Pull request by jeffkaufman**
* refactor time handling
* add caching of pr_json from github
* add a notion of the number of days a PR has been sitting

This is #29 with all the functionality changes removed.

### CODE REVIEW

**Comment by pavellishin** [comment]
Oh no, conflicts!

**Comment by jeffkaufman** [comment]
> Oh no, conflicts!

addressed in 0edbac9; needs re-review :(

**Comment by jeffkaufman** [comment]
@TheJhyde 

> You'd have to edit the merge timestamp, which doesn't seem cricket to me.

This PR uses the timestamps github provides, which I think come from GitHub's internal records and not from git.

**Comment by TheJhyde** [comment]
Yes, the PR prevents any kind of chicanery from git timestamps. I had been delaying approving it up until now because I'd hoped to engage in some of that chicanery.

**Comment by pavellishin** [comment]
That would have been a beautiful way to win, tbh.

**Pull request merged**
