### PR TITLE
Player Scores

### PR DESCRIPTION
**Pull request by TheJhyde**
Gives each player 10 points. The purpose of points has not yet been established but with them in place, the potential exists for them to be used for something. Future players will be responsible for giving themselves 10 points when they join the game.

### CODE REVIEW

**Comment by TheJhyde** [comment]
What if I can make it worth your while, will you approve it then?

**Comment by tnelling** [comment]
I do appreciate your audacity. I'm curious to see what other people think of this.

**Comment by jeffkaufman** [comment]
Overall, I like having points files as a way to make a PR that does (a) something person X doesn't like but (b) give person X some points in exchange so you still can get their approval.

**Comment by TheJhyde** [comment]
I've updated the PR to fix a conflict with the new README file and to give vesche points.

**Comment by TheJhyde** [comment]
I think @tnelling needs to switch his request for changes to an approval and then this can be merged.

**Pull request merged**
